// <auto-generated />
using AddressAPI3.EFData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressAPI3.EFData.Migrations
{
    [DbContext(typeof(AddressContext))]
    [Migration("20181010152619_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressAPI3.EFData.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuildingName")
                        .HasMaxLength(50);

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(4);

                    b.Property<string>("Department")
                        .HasMaxLength(60);

                    b.Property<string>("Locality")
                        .HasMaxLength(35);

                    b.Property<string>("LocalityDependent")
                        .HasMaxLength(35);

                    b.Property<string>("Organisation")
                        .HasMaxLength(60);

                    b.Property<string>("POBox")
                        .HasMaxLength(6);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PostcodeDisplay")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("SubBuildingName")
                        .HasMaxLength(30);

                    b.Property<string>("Thoroughfare")
                        .HasMaxLength(80);

                    b.Property<string>("ThoroughfareDependent")
                        .HasMaxLength(80);

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AddressAPI3.EFData.Entities.Postcode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<int>("Count");

                    b.Property<string>("Description")
                        .HasMaxLength(80);

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Postcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
